Change - Update puppetlabs-concat module from v. 1.1.0 to 1.2.5.
This commit fixes the following error which is caused by the old concat
module.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 0
is not a string.  It looks to be a Fixnum on node mdct-dev27.dartcontainer.com